version: '2.3'
services:
  app:
    build: .
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    ports:
      - "8000:8000"
    entrypoint: ["python", "main.py"]